version: '3.9'

services:
    buymezobo:
        container_name: buymezobo
        build:
           context: .
           dockerfile: next.dockerfile
        restart: always
        env_file:
            - .env
        ports:
            - 3000:3000



