export const HomePageWords = [
	'creative work',
	'programming project',
	'small business',
	'startup idea',
	'art project',
	'music career',
	'writing endeavor',
	'nonprofit organization',
	'community initiative',
	'educational course',
	'research project',
	'design studio',
	'photography business',
	'tech venture',
	'film production',
	'craft shop',
	'event planning service',
	'fashion line',
	'wellness program',
	'fitness journey',
	'travel blog',
	'cooking channel',
	'garden project',
	'DIY project',
	'content creation',
	'online store',
	'charity event',
];
