export const ProfileTagsOptions = [
	{ label: 'Education', value: 'education' },
	{ label: 'Writing', value: 'writing' },
	{ label: 'Video and Film', value: 'video_and_film' },
	{ label: 'Art', value: 'art' },
	{ label: 'Photography', value: 'photography' },
	{ label: 'Graphic Design', value: 'graphic_design' },
	{ label: 'Music', value: 'music' },
	{ label: 'Technology', value: 'technology' },
	{ label: 'Science', value: 'science' },
	{ label: 'Health and Wellness', value: 'health_and_wellness' },
	{ label: 'Fitness', value: 'fitness' },
	{ label: 'Travel', value: 'travel' },
	{ label: 'Food and Drink', value: 'food_and_drink' },
	{ label: 'Cooking', value: 'cooking' },
	{ label: 'Fashion', value: 'fashion' },
	{ label: 'Beauty', value: 'beauty' },
	{ label: 'Sports', value: 'sports' },
	{ label: 'Gaming', value: 'gaming' },
	{ label: 'Lifestyle', value: 'lifestyle' },
	{ label: 'Personal Development', value: 'personal_development' },
	{ label: 'Finance', value: 'finance' },
	{ label: 'Investment', value: 'investment' },
	{ label: 'Entrepreneurship', value: 'entrepreneurship' },
	{ label: 'Marketing', value: 'marketing' },
	{ label: 'Advertising', value: 'advertising' },
	{ label: 'Public Relations', value: 'public_relations' },
	{ label: 'Social Media', value: 'social_media' },
	{ label: 'Blogging', value: 'blogging' },
	{ label: 'Podcasting', value: 'podcasting' },
	{ label: 'Crafts', value: 'crafts' },
	{ label: 'DIY Projects', value: 'diy_projects' },
	{ label: 'Home Improvement', value: 'home_improvement' },
	{ label: 'Gardening', value: 'gardening' },
	{ label: 'Parenting', value: 'parenting' },
	{ label: 'Relationships', value: 'relationships' },
	{ label: 'Pets', value: 'pets' },
	{ label: 'Spirituality', value: 'spirituality' },
	{ label: 'Mindfulness', value: 'mindfulness' },
	{ label: 'Meditation', value: 'meditation' },
	{ label: 'Yoga', value: 'yoga' },
	{ label: 'Dance', value: 'dance' },
	{ label: 'Theater', value: 'theater' },
	{ label: 'Comedy', value: 'comedy' },
	{ label: 'Acting', value: 'acting' },
	{ label: 'Modeling', value: 'modeling' },
	{ label: 'Journalism', value: 'journalism' },
	{ label: 'History', value: 'history' },
	{ label: 'Politics', value: 'politics' },
	{ label: 'Culture', value: 'culture' },
	{ label: 'Languages', value: 'languages' },
	{ label: 'Coding', value: 'coding' },
	{ label: 'Software Development', value: 'software_development' },
	{ label: 'Web Development', value: 'web_development' },
	{ label: 'App Development', value: 'app_development' },
	{ label: 'Artificial Intelligence', value: 'artificial_intelligence' },
	{ label: 'Machine Learning', value: 'machine_learning' },
	{ label: 'Data Science', value: 'data_science' },
	{ label: 'Cybersecurity', value: 'cybersecurity' },
	{ label: 'Blockchain', value: 'blockchain' },
	{ label: 'Cryptocurrency', value: 'cryptocurrency' },
	{ label: 'Virtual Reality', value: 'virtual_reality' },
	{ label: 'Augmented Reality', value: 'augmented_reality' },
	{ label: 'Robotics', value: 'robotics' },
	{ label: 'Automotive', value: 'automotive' },
	{ label: 'Real Estate', value: 'real_estate' },
	{ label: 'Interior Design', value: 'interior_design' },
	{ label: 'Architecture', value: 'architecture' },
	{ label: 'Environmentalism', value: 'environmentalism' },
	{ label: 'Sustainability', value: 'sustainability' },
	{ label: 'Wildlife', value: 'wildlife' },
	{ label: 'Astronomy', value: 'astronomy' },
	{ label: 'Mathematics', value: 'mathematics' },
	{ label: 'Physics', value: 'physics' },
	{ label: 'Chemistry', value: 'chemistry' },
	{ label: 'Biology', value: 'biology' },
	{ label: 'Geology', value: 'geology' },
	{ label: 'Meteorology', value: 'meteorology' },
	{ label: 'Oceanography', value: 'oceanography' },
	{ label: 'Paleontology', value: 'paleontology' },
	{ label: 'Agriculture', value: 'agriculture' },
	{ label: 'Forestry', value: 'forestry' },
	{ label: 'Fishing', value: 'fishing' },
	{ label: 'Hunting', value: 'hunting' },
	{ label: 'Survival Skills', value: 'survival_skills' },
	{ label: 'Adventure', value: 'adventure' },
	{ label: 'Hiking', value: 'hiking' },
	{ label: 'Camping', value: 'camping' },
	{ label: 'Climbing', value: 'climbing' },
	{ label: 'Skiing', value: 'skiing' },
	{ label: 'Snowboarding', value: 'snowboarding' },
	{ label: 'Surfing', value: 'surfing' },
	{ label: 'Scuba Diving', value: 'scuba_diving' },
	{ label: 'Sailing', value: 'sailing' },
	{ label: 'Boating', value: 'boating' },
	{ label: 'Motorcycling', value: 'motorcycling' },
	{ label: 'Cycling', value: 'cycling' },
	{ label: 'Running', value: 'running' },
	{ label: 'Walking', value: 'walking' },
	{ label: 'Skateboarding', value: 'skateboarding' },
	{ label: 'Rollerblading', value: 'rollerblading' },
	{ label: 'E-sports', value: 'e_sports' },
	{ label: 'Board Games', value: 'board_games' },
	{ label: 'Card Games', value: 'card_games' },
	{ label: 'Magic Tricks', value: 'magic_tricks' },
	{ label: 'Puzzles', value: 'puzzles' },
	{ label: 'Origami', value: 'origami' },
	{ label: 'Knitting', value: 'knitting' },
	{ label: 'Sewing', value: 'sewing' },
	{ label: 'Embroidery', value: 'embroidery' },
	{ label: 'Quilting', value: 'quilting' },
	{ label: 'Baking', value: 'baking' },
	{ label: 'Barbecuing', value: 'barbecuing' },
	{ label: 'Mixology', value: 'mixology' },
	{ label: 'Wine Tasting', value: 'wine_tasting' },
	{ label: 'Beer Brewing', value: 'beer_brewing' },
	{ label: 'Tea Culture', value: 'tea_culture' },
	{ label: 'Coffee Culture', value: 'coffee_culture' },
	{ label: 'Veganism', value: 'veganism' },
	{ label: 'Vegetarianism', value: 'vegetarianism' },
	{ label: 'Mediterranean Diet', value: 'mediterranean_diet' },
	{ label: 'Paleo Diet', value: 'paleo_diet' },
	{ label: 'Keto Diet', value: 'keto_diet' },
	{ label: 'Gluten-Free Cooking', value: 'gluten_free_cooking' },
	{ label: 'Ethnic Cuisine', value: 'ethnic_cuisine' },
];
