export const ProfileTagsOptions = [
	{ label: 'Education', value: 'education', color: '#581C87' },
	{ label: 'Writing', value: 'writing', color: '#581C87' },
	{ label: 'Video and Film', value: 'video_and_film', color: '#581C87' },
	{ label: 'Art', value: 'art', color: '#581C87' },
	{ label: 'Photography', value: 'photography', color: '#581C87' },
	{ label: 'Graphic Design', value: 'graphic_design', color: '#581C87' },
	{ label: 'Music', value: 'music', color: '#581C87' },
	{ label: 'Technology', value: 'technology', color: '#581C87' },
	{ label: 'Science', value: 'science', color: '#581C87' },
	{ label: 'Health and Wellness', value: 'health_and_wellness', color: '#581C87' },
	{ label: 'Fitness', value: 'fitness', color: '#581C87' },
	{ label: 'Travel', value: 'travel', color: '#581C87' },
	{ label: 'Food and Drink', value: 'food_and_drink', color: '#581C87' },
	{ label: 'Cooking', value: 'cooking', color: '#581C87' },
	{ label: 'Fashion', value: 'fashion', color: '#581C87' },
	{ label: 'Beauty', value: 'beauty', color: '#581C87' },
	{ label: 'Sports', value: 'sports', color: '#581C87' },
	{ label: 'Gaming', value: 'gaming', color: '#581C87' },
	{ label: 'Lifestyle', value: 'lifestyle', color: '#581C87' },
	{ label: 'Personal Development', value: 'personal_development', color: '#581C87' },
	{ label: 'Finance', value: 'finance', color: '#581C87' },
	{ label: 'Investment', value: 'investment', color: '#581C87' },
	{ label: 'Entrepreneurship', value: 'entrepreneurship', color: '#581C87' },
	{ label: 'Marketing', value: 'marketing', color: '#581C87' },
	{ label: 'Advertising', value: 'advertising', color: '#581C87' },
	{ label: 'Public Relations', value: 'public_relations', color: '#581C87' },
	{ label: 'Social Media', value: 'social_media', color: '#581C87' },
	{ label: 'Blogging', value: 'blogging', color: '#581C87' },
	{ label: 'Podcasting', value: 'podcasting', color: '#581C87' },
	{ label: 'Crafts', value: 'crafts', color: '#581C87' },
	{ label: 'DIY Projects', value: 'diy_projects', color: '#581C87' },
	{ label: 'Home Improvement', value: 'home_improvement', color: '#581C87' },
	{ label: 'Gardening', value: 'gardening', color: '#581C87' },
	{ label: 'Parenting', value: 'parenting', color: '#581C87' },
	{ label: 'Relationships', value: 'relationships', color: '#581C87' },
	{ label: 'Pets', value: 'pets', color: '#581C87' },
	{ label: 'Spirituality', value: 'spirituality', color: '#581C87' },
	{ label: 'Mindfulness', value: 'mindfulness', color: '#581C87' },
	{ label: 'Meditation', value: 'meditation', color: '#581C87' },
	{ label: 'Yoga', value: 'yoga', color: '#581C87' },
	{ label: 'Dance', value: 'dance', color: '#581C87' },
	{ label: 'Theater', value: 'theater', color: '#581C87' },
	{ label: 'Comedy', value: 'comedy', color: '#581C87' },
	{ label: 'Acting', value: 'acting', color: '#581C87' },
	{ label: 'Modeling', value: 'modeling', color: '#581C87' },
	{ label: 'Journalism', value: 'journalism', color: '#581C87' },
	{ label: 'History', value: 'history', color: '#581C87' },
	{ label: 'Politics', value: 'politics', color: '#581C87' },
	{ label: 'Culture', value: 'culture', color: '#581C87' },
	{ label: 'Languages', value: 'languages', color: '#581C87' },
	{ label: 'Coding', value: 'coding', color: '#581C87' },
	{ label: 'Software Development', value: 'software_development', color: '#581C87' },
	{ label: 'Web Development', value: 'web_development', color: '#581C87' },
	{ label: 'App Development', value: 'app_development', color: '#581C87' },
	{ label: 'Artificial Intelligence', value: 'artificial_intelligence', color: '#581C87' },
	{ label: 'Machine Learning', value: 'machine_learning', color: '#581C87' },
	{ label: 'Data Science', value: 'data_science', color: '#581C87' },
	{ label: 'Cybersecurity', value: 'cybersecurity', color: '#581C87' },
	{ label: 'Blockchain', value: 'blockchain', color: '#581C87' },
	{ label: 'Cryptocurrency', value: 'cryptocurrency', color: '#581C87' },
	{ label: 'Virtual Reality', value: 'virtual_reality', color: '#581C87' },
	{ label: 'Augmented Reality', value: 'augmented_reality', color: '#581C87' },
	{ label: 'Robotics', value: 'robotics', color: '#581C87' },
	{ label: 'Automotive', value: 'automotive', color: '#581C87' },
	{ label: 'Real Estate', value: 'real_estate', color: '#581C87' },
	{ label: 'Interior Design', value: 'interior_design', color: '#581C87' },
	{ label: 'Architecture', value: 'architecture', color: '#581C87' },
	{ label: 'Environmentalism', value: 'environmentalism', color: '#581C87' },
	{ label: 'Sustainability', value: 'sustainability', color: '#581C87' },
	{ label: 'Wildlife', value: 'wildlife', color: '#581C87' },
	{ label: 'Astronomy', value: 'astronomy', color: '#581C87' },
	{ label: 'Mathematics', value: 'mathematics', color: '#581C87' },
	{ label: 'Physics', value: 'physics', color: '#581C87' },
	{ label: 'Chemistry', value: 'chemistry', color: '#581C87' },
	{ label: 'Biology', value: 'biology', color: '#581C87' },
	{ label: 'Geology', value: 'geology', color: '#581C87' },
	{ label: 'Meteorology', value: 'meteorology', color: '#581C87' },
	{ label: 'Oceanography', value: 'oceanography', color: '#581C87' },
	{ label: 'Paleontology', value: 'paleontology', color: '#581C87' },
	{ label: 'Agriculture', value: 'agriculture', color: '#581C87' },
	{ label: 'Forestry', value: 'forestry', color: '#581C87' },
	{ label: 'Fishing', value: 'fishing', color: '#581C87' },
	{ label: 'Hunting', value: 'hunting', color: '#581C87' },
	{ label: 'Survival Skills', value: 'survival_skills', color: '#581C87' },
	{ label: 'Adventure', value: 'adventure', color: '#581C87' },
	{ label: 'Hiking', value: 'hiking', color: '#581C87' },
	{ label: 'Camping', value: 'camping', color: '#581C87' },
	{ label: 'Climbing', value: 'climbing', color: '#581C87' },
	{ label: 'Skiing', value: 'skiing', color: '#581C87' },
	{ label: 'Snowboarding', value: 'snowboarding', color: '#581C87' },
	{ label: 'Surfing', value: 'surfing', color: '#581C87' },
	{ label: 'Scuba Diving', value: 'scuba_diving', color: '#581C87' },
	{ label: 'Sailing', value: 'sailing', color: '#581C87' },
	{ label: 'Boating', value: 'boating', color: '#581C87' },
	{ label: 'Motorcycling', value: 'motorcycling', color: '#581C87' },
	{ label: 'Cycling', value: 'cycling', color: '#581C87' },
	{ label: 'Running', value: 'running', color: '#581C87' },
	{ label: 'Walking', value: 'walking', color: '#581C87' },
	{ label: 'Skateboarding', value: 'skateboarding', color: '#581C87' },
	{ label: 'Rollerblading', value: 'rollerblading', color: '#581C87' },
	{ label: 'E-sports', value: 'e_sports', color: '#581C87' },
	{ label: 'Board Games', value: 'board_games', color: '#581C87' },
	{ label: 'Card Games', value: 'card_games', color: '#581C87' },
	{ label: 'Magic Tricks', value: 'magic_tricks', color: '#581C87' },
	{ label: 'Puzzles', value: 'puzzles', color: '#581C87' },
	{ label: 'Origami', value: 'origami', color: '#581C87' },
	{ label: 'Knitting', value: 'knitting', color: '#581C87' },
	{ label: 'Sewing', value: 'sewing', color: '#581C87' },
	{ label: 'Embroidery', value: 'embroidery', color: '#581C87' },
	{ label: 'Quilting', value: 'quilting', color: '#581C87' },
	{ label: 'Baking', value: 'baking', color: '#581C87' },
	{ label: 'Barbecuing', value: 'barbecuing', color: '#581C87' },
	{ label: 'Mixology', value: 'mixology', color: '#581C87' },
	{ label: 'Wine Tasting', value: 'wine_tasting', color: '#581C87' },
	{ label: 'Beer Brewing', value: 'beer_brewing', color: '#581C87' },
	{ label: 'Tea Culture', value: 'tea_culture', color: '#581C87' },
	{ label: 'Coffee Culture', value: 'coffee_culture', color: '#581C87' },
	{ label: 'Veganism', value: 'veganism', color: '#581C87' },
	{ label: 'Vegetarianism', value: 'vegetarianism', color: '#581C87' },
	{ label: 'Mediterranean Diet', value: 'mediterranean_diet', color: '#581C87' },
	{ label: 'Paleo Diet', value: 'paleo_diet', color: '#581C87' },
	{ label: 'Keto Diet', value: 'keto_diet', color: '#581C87' },
	{ label: 'Gluten-Free Cooking', value: 'gluten_free_cooking', color: '#581C87' },
	{ label: 'Ethnic Cuisine', value: 'ethnic_cuisine', color: '#581C87' },
];
